// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $AddToCartBuyTogether_vtex from "./islands/AddToCartBuyTogether/vtex.tsx";
import * as $BackToTop from "./islands/BackToTop.tsx";
import * as $ClickZoomImage from "./islands/ClickZoomImage.tsx";
import * as $CustomBuyTogetherContent from "./islands/CustomBuyTogetherContent.tsx";
import * as $CustomSkuSelector from "./islands/CustomSkuSelector.tsx";
import * as $EmptySearchParams from "./islands/EmptySearchParams.tsx";
import * as $Filter from "./islands/Filter.tsx";
import * as $FilterRangePrice from "./islands/FilterRangePrice.tsx";
import * as $FilterResult from "./islands/FilterResult.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $KitLookBuyButton_KitLookBuyButton from "./islands/KitLookBuyButton/KitLookBuyButton.tsx";
import * as $KitLookBuyButton_vtexKitLook from "./islands/KitLookBuyButton/vtexKitLook.tsx";
import * as $KitLookImage from "./islands/KitLookImage.tsx";
import * as $MenuTabs from "./islands/MenuTabs.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductKitLook from "./islands/ProductKitLook.tsx";
import * as $ProductMobileTabs from "./islands/ProductMobileTabs.tsx";
import * as $ProductQuickBuy from "./islands/ProductQuickBuy.tsx";
import * as $ProductSizeList from "./islands/ProductSizeList.tsx";
import * as $QuickBuyButton_QuickBuyButton from "./islands/QuickBuyButton/QuickBuyButton.tsx";
import * as $QuickBuyImageSlider from "./islands/QuickBuyImageSlider.tsx";
import * as $QuickBuySizeList from "./islands/QuickBuySizeList.tsx";
import * as $ScrollHeader from "./islands/ScrollHeader.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Sort from "./islands/Sort.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/AddToCartBuyTogether/vtex.tsx": $AddToCartBuyTogether_vtex,
    "./islands/BackToTop.tsx": $BackToTop,
    "./islands/ClickZoomImage.tsx": $ClickZoomImage,
    "./islands/CustomBuyTogetherContent.tsx": $CustomBuyTogetherContent,
    "./islands/CustomSkuSelector.tsx": $CustomSkuSelector,
    "./islands/EmptySearchParams.tsx": $EmptySearchParams,
    "./islands/Filter.tsx": $Filter,
    "./islands/FilterRangePrice.tsx": $FilterRangePrice,
    "./islands/FilterResult.tsx": $FilterResult,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/KitLookBuyButton/KitLookBuyButton.tsx":
      $KitLookBuyButton_KitLookBuyButton,
    "./islands/KitLookBuyButton/vtexKitLook.tsx": $KitLookBuyButton_vtexKitLook,
    "./islands/KitLookImage.tsx": $KitLookImage,
    "./islands/MenuTabs.tsx": $MenuTabs,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductKitLook.tsx": $ProductKitLook,
    "./islands/ProductMobileTabs.tsx": $ProductMobileTabs,
    "./islands/ProductQuickBuy.tsx": $ProductQuickBuy,
    "./islands/ProductSizeList.tsx": $ProductSizeList,
    "./islands/QuickBuyButton/QuickBuyButton.tsx":
      $QuickBuyButton_QuickBuyButton,
    "./islands/QuickBuyImageSlider.tsx": $QuickBuyImageSlider,
    "./islands/QuickBuySizeList.tsx": $QuickBuySizeList,
    "./islands/ScrollHeader.tsx": $ScrollHeader,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Sort.tsx": $Sort,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
