export const sizeMappings = [
  { "size": "RN" },
  { "size": "P" },
  { "size": "M" },
  { "size": "G" },
  { "size": "GG" },
  { "size": "1" },
  { "size": "2" },
  { "size": "3" },
  { "size": "4" },
  { "size": "5" },
  { "size": "6" },
  { "size": "7" },
  { "size": "8" },
  { "size": "9" },
  { "size": "10" },
  { "size": "11" },
  { "size": "12" },
  { "size": "13" },
  { "size": "14" },
  { "size": "15" },
  { "size": "16" },
  { "size": "17" },
  { "size": "18" },
  { "size": "19" },
  { "size": "20" },
];
